### ISSUE TITLE
sharing link got bug, can not jump to the publish work

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#153] opened 2022-05-21 13:47 UTC
## What's going wrong?

the sharing link got some problems, can not go jump

## How to reproduce?

1. Go generate a sharing link
2.  paste it on board
3. and the sharing link is :**You are welcome to view and try casting my NFT publication: https://sparklink.io/#/spark/[object Object]/[object Object]**
4. there are some "[object Object]" behand the link, can not open the web tho
 you can see it just like the gif below

![bug](https://user-images.githubusercontent.com/92965123/169654410-5ff7dc43-f8f7-4d3d-9cb5-a878bf673a10.gif)

If inapplicable, just leave a `no need for this issue` mark.

## Expected behavior

please make sure the sharing link can run if anyone uses  @it

## Context

refactor branch.

**Comment by SantanaSP** [comment] 2022-05-21 19:40
Which version?

**Comment by SantanaSP** [comment] 2022-05-21 20:03
Duplicate of #146 .

**Comment by Erreth-Akbe** [comment] 2022-05-22 06:29
Why Duplicate of #146. Is it because of the wrong use of the script?

**Comment by SantanaSP** [comment] 2022-05-22 06:35
My fault, its not a duplicate. I'll check and fix it.

**Closed as completed** 2022-05-22 10:23 UTC
Labels: bug, emegency
